Fixes CVE-2020-20907.
Desc:
  In Lib/tarfile.py in Python through 3.8.3, an attacker is able to craft a TAR
  archive leading to an infinite loop when opened by tarfile.open, because
  _proc_pax lacks header validation.

Upstream bug: https://bugs.python.org/issue39017

Upstream commit:
https://github.com/python/cpython/commit/79c6b602efc9a906c8496f3d5f4d54c54b48fa06

--- Python-3.7.8/Lib/tarfile.py
+++ Python-3.7.8/Lib/tarfile.py
@@ -1233,6 +1233,8 @@ def _proc_pax(self, tarfile):
 
             length, keyword = match.groups()
             length = int(length)
+            if length == 0:
+                raise InvalidHeaderError("invalid header")
             value = buf[match.end(2) + 1:match.start(1) + length - 1]
 
             # Normally, we could just use "utf-8" as the encoding and "strict"
